### ISSUE TITLE
Increase repeat count for the loop mode 

### ISSUE THREAD

**Issue by tieyongyin** [mcci-usb/Cricket#132]
Hello,
can you please increase the repeat count for the loop mode test? currently only 999 is allowed as maximum repeat count. could you please increase it to at lease 10,000? thanks. 
![Loop Repeat Count](https://github.com/mcci-usb/Cricket/assets/150970619/f837c54d-910b-4136-9f0d-d33bf27aff2b)

**Comment by vinaynmcci** [comment]
Sure, I will increase the Repeat count up to 10,000 in Cricket UI source.

**Comment by vinaynmcci** [comment]
Hello tieyongyin,

we are working on increasing the **repeat count** issue and plan to release the fix in an upcoming patch release.

Thanks..
