### ISSUE TITLE
Security threat alert in Windows

### ISSUE THREAD

**Issue by vseenivasan** [mcci-usb/Cricket#35]
After installing the application in Windows, defender alerts about a thread "TROJ.Win32.TRX.XXPE..."

**Comment by MuruganChandrasekar** [comment]
Hello Seenivasan,

With this threat regards, I've  done the following steps on the system where the "Cricket" EXE created:
- Uninstalled Python software (3.7.6) and Pyinstaller (4.5.0) and other dependencies.
- Did the Windows 10 update.
- Scanned full system with Antivirus; but, it said "no threats found".
- Again, Installed Python software (3.7.6) and Pyinstaller (4.7) and other dependencies.
- Asked Developer to create the "Cricket" EXE and tested it on other systems with Windows Defender. It's working well.
