### ISSUE TITLE
Connecting to switch with manual control doesn't reflect switch state

### ISSUE THREAD

**Issue by terrillmoore** [mcci-usb/Cricket#64]
System: Windows 10 / 64; 1 host controller, 12 hubs, 18 peripherals
Cricket UI: v2.4 or v2.5
Switch: Model 2101

## Repro: 
1. manually connect the switch to a device using the switch. Use the "high-speed only" button to make the connection.
2. launch the app
3. connect to the switch

## Desired behavior:
UI shows switch state (both connected, and superspeed disabled).

## Actual behavior:
UI shows switch as disconnected, with superspeed enabled.

**Comment by vseenivasan** [comment]
Code updated to read the status of 2101, merged in v3.0.0
