### ISSUE TITLE
Device search dialog goes blank until complete the search 

### ISSUE THREAD

**Issue by vseenivasan** [mcci-usb/Cricket#70]
The Device search dialog goes blank when initiate device search, until complete the search all widgets are displayed without caption. This is happening in Windows and Linux.

**Comment by svelmurugan92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🤞 This Card is todo - but the team is not committed to completing it yet](https://trello.com/c/lSRjkvWP/8-%F0%9F%A4%9E-this-card-is-todo-but-the-team-is-not-committed-to-completing-it-yet)
