### ISSUE TITLE
No switch connected on Linux; UI seems to show a 2101

### ISSUE THREAD

**Issue by terrillmoore** [mcci-usb/Cricket#83]
![image](https://user-images.githubusercontent.com/19333103/188520098-b0dd6e4f-80d1-4ce9-9afd-e7730f005576.png)
Note that the port off switch is visually enabled, and the upper left box shows `MCCI USB Switch 2101`. The opert on/off switch should be grayed out, and the upper left box label should be `No switch selected`.

When you then press connect, you get this:
![image](https://user-images.githubusercontent.com/19333103/188520193-157dda93-42f6-449c-a271-b3837c19c19c.png)
Note the strange button next to connect; and the [Search] button is not three-dimensional and visually enabled (although you can click on it and cause another search).

**Comment by svelmurugan92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CricketApi development](https://trello.com/c/ela7WiYF/18-cricketapi-development)
